export const assetData = [
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Laptops and Computers",
      Depreciation_Rate: 40,
      ItemCode: "COM",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Servers and Server Racks",
      Depreciation_Rate: 40,
      ItemCode: "SSR",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Servers and Server Racks",
      Depreciation_Rate: 40,
      ItemCode: "SSR",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Networking Equipment",
      Depreciation_Rate: 15,
      ItemCode: "NET",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Printers & Scanners",
      Depreciation_Rate: 15,
      ItemCode: "PSP",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Projectors and Conference Room Equipment",
      Depreciation_Rate: 15,
      ItemCode: "PCE",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Office Furniture",
      Depreciation_Rate: 10,
      ItemCode: "FUR",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Televisions and Display Screens",
      Depreciation_Rate: 15,
      ItemCode: "TVS",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Software Licenses",
      Depreciation_Rate: 40,
      ItemCode: "SWL",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Operating Systems",
      Depreciation_Rate: 40,
      ItemCode: "OSY",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "CRM Software",
      Depreciation_Rate: 40,
      ItemCode: "CRM",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "ERP Software",
      Depreciation_Rate: 40,
      ItemCode: "ERP",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Cybersecurity Software",
      Depreciation_Rate: 40,
      ItemCode: "CSS",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Air Conditioning Units",
      Depreciation_Rate: 15,
      ItemCode: "ACU",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Heating Systems",
      Depreciation_Rate: 15,
      ItemCode: "HTS",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Security Systems",
      Depreciation_Rate: 15,
      ItemCode: "SEC",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Fire Safety Equipment",
      Depreciation_Rate: 15,
      ItemCode: "FSE",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Specialized Testing Devices",
      Depreciation_Rate: 15,
      ItemCode: "STD",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "High-Resolution Monitors for Design Work",
      Depreciation_Rate: 15,
      ItemCode: "HRM",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Monitors",
      Depreciation_Rate: 40,
      ItemCode: "MON",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Keyboards and Mice",
      Depreciation_Rate: 40,
      ItemCode: "KAM",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Docking Stations",
      Depreciation_Rate: 40,
      ItemCode: "DOC",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "External Storage Devices",
      Depreciation_Rate: 40,
      ItemCode: "ESD",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Webcams and Headsets",
      Depreciation_Rate: 40,
      ItemCode: "WAH",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "UPS",
      Depreciation_Rate: 15,
      ItemCode: "UPS",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Decorations and Artwork",
      Depreciation_Rate: 10,
      ItemCode: "ART",
    },
    {
      Category: "CONSUMABLES",
      Item: "Indoor Plants",
      Depreciation_Rate: 100,
      ItemCode: "PLT",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Framed Certifications and Achievements",
      Depreciation_Rate: 10,
      ItemCode: "FCA",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Smartphones",
      Depreciation_Rate: 15,
      ItemCode: "SMP",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Tablets",
      Depreciation_Rate: 15,
      ItemCode: "TAB",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Office Phones",
      Depreciation_Rate: 15,
      ItemCode: "OFP",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Video Conferencing Equipment",
      Depreciation_Rate: 15,
      ItemCode: "VCE",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Development Boards (Arduino, Raspberry Pi)",
      Depreciation_Rate: 40,
      ItemCode: "DBD",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Graphic Tablets",
      Depreciation_Rate: 15,
      ItemCode: "GRT",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Content Creation Equipment",
      Depreciation_Rate: 15,
      ItemCode: "SCC",
    },
    {
      Category: "CONSUMABLES",
      Item: "Stationery",
      Depreciation_Rate: 100,
      ItemCode: "STA",
    },
    {
      Category: "CONSUMABLES",
      Item: "Printer Supplies",
      Depreciation_Rate: 100,
      ItemCode: "PSU",
    },
    {
      Category: "CONSUMABLES",
      Item: "Post-it Notes",
      Depreciation_Rate: 100,
      ItemCode: "PIN",
    },
    {
      Category: "CONSUMABLES",
      Item: "Whiteboards and Markers",
      Depreciation_Rate: 100,
      ItemCode: "WBM",
    },
    {
      Category: "CONSUMABLES",
      Item: "Non-Rechargeable Batteries",
      Depreciation_Rate: 100,
      ItemCode: "NRB",
    },
    {
      Category: "DEPRECIABLE_ASSET",
      Item: "Rechargeable Batteries",
      Depreciation_Rate: 15,
      ItemCode: "RCB",
    },
    {
      Category: "CONSUMABLES",
      Item: "General Cleaning Supplies",
      Depreciation_Rate: 100,
      ItemCode: "GCS",
    },
    {
      Category: "CONSUMABLES",
      Item: "Light Bulbs",
      Depreciation_Rate: 100,
      ItemCode: "LBL",
    },
    {
      Category: "CONSUMABLES",
      Item: "Hand Sanitizers",
      Depreciation_Rate: 100,
      ItemCode: "HNS",
    },
    {
      Category: "CONSUMABLES",
      Item: "Coffee and Tea Supplies",
      Depreciation_Rate: 100,
      ItemCode: "CTS",
    },
    {
      Category: "CONSUMABLES",
      Item: "Snacks and Refreshments",
      Depreciation_Rate: 100,
      ItemCode: "SNR",
    },
    {
      Category: "CONSUMABLES",
      Item: "Water Dispensers and Water Bottles",
      Depreciation_Rate: 100,
      ItemCode: "WDW",
    },
    {
      Category: "CONSUMABLES",
      Item: "First Aid Kits",
      Depreciation_Rate: 100,
      ItemCode: "FAK",
    },
    {
      Category: "CONSUMABLES",
      Item: "Business Cards",
      Depreciation_Rate: 100,
      ItemCode: "BCR",
    },
    {
      Category: "CONSUMABLES",
      Item: "Marketing Materials",
      Depreciation_Rate: 100,
      ItemCode: "MAM",
    },
    {
      Category: "CONSUMABLES",
      Item: "Subscriptions",
      Depreciation_Rate: 100,
      ItemCode: "SUB",
    },
    {
      Category: "CONSUMABLES",
      Item: "Pantry Supplies",
      Depreciation_Rate: 100,
      ItemCode: "OKS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Electricity",
      Depreciation_Rate: 100,
      ItemCode: "ELE",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Internet Service",
      Depreciation_Rate: 100,
      ItemCode: "INT",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Water",
      Depreciation_Rate: 100,
      ItemCode: "WAT",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Waste Disposal",
      Depreciation_Rate: 100,
      ItemCode: "WAD",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Office Rent (194I10)",
      Depreciation_Rate: 100,
      ItemCode: "OFR",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Director's Commission (194J10)",
      Depreciation_Rate: 100,
      ItemCode: "DIC",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Insurance Consultation (194D5)",
      Depreciation_Rate: 100,
      ItemCode: "INC",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Medical Services (194J10)",
      Depreciation_Rate: 100,
      ItemCode: "MES",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Legal Services (194J10)",
      Depreciation_Rate: 100,
      ItemCode: "LES",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Architectural Services (194J10)",
      Depreciation_Rate: 100,
      ItemCode: "ARS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Engineering Services (194J10)",
      Depreciation_Rate: 100,
      ItemCode: "ENS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Advertising Services (194J10)",
      Depreciation_Rate: 100,
      ItemCode: "ADS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Technical Consultancy Services (194J10)",
      Depreciation_Rate: 100,
      ItemCode: "TCS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Interior Decoration Services (194J10)",
      Depreciation_Rate: 100,
      ItemCode: "IDS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Accountancy Services (194J10)",
      Depreciation_Rate: 100,
      ItemCode: "ACS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Technical Services (194J2)",
      Depreciation_Rate: 100,
      ItemCode: "TES",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Managerial Services  (194J2)",
      Depreciation_Rate: 100,
      ItemCode: "MAS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Consultation & Advisory Service (194J2)",
      Depreciation_Rate: 100,
      ItemCode: "CAS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Janitorial Services (194C2)",
      Depreciation_Rate: 100,
      ItemCode: "JAS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Catering Services (194C2)",
      Depreciation_Rate: 100,
      ItemCode: "CTS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "SaaS Subscriptions",
      Depreciation_Rate: 100,
      ItemCode: "SAS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Insurance Premium",
      Depreciation_Rate: 100,
      ItemCode: "INS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Foreign Travel Expenses",
      Depreciation_Rate: 100,
      ItemCode: "FTE",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Domestic Travel Expenses",
      Depreciation_Rate: 100,
      ItemCode: "DTE",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Meals and Entertainment",
      Depreciation_Rate: 100,
      ItemCode: "MEE",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Souvenirs",
      Depreciation_Rate: 100,
      ItemCode: "SOU",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Bus",
      Depreciation_Rate: 100,
      ItemCode: "BTB",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Train",
      Depreciation_Rate: 100,
      ItemCode: "BTT",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Ferry",
      Depreciation_Rate: 100,
      ItemCode: "BTF",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Meals",
      Depreciation_Rate: 100,
      ItemCode: "BTM",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Cab",
      Depreciation_Rate: 100,
      ItemCode: "BTC",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Daily Needs",
      Depreciation_Rate: 100,
      ItemCode: "BTD",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Laundry",
      Depreciation_Rate: 100,
      ItemCode: "BTL",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Service Tip",
      Depreciation_Rate: 100,
      ItemCode: "BTT",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Grooming Essentials",
      Depreciation_Rate: 100,
      ItemCode: "BGE",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Consultation & HR",
      Depreciation_Rate: 100,
      ItemCode: "BCH",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Sightseeing",
      Depreciation_Rate: 100,
      ItemCode: "BSS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Conference",
      Depreciation_Rate: 100,
      ItemCode: "BTC",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour Souvenirs",
      Depreciation_Rate: 100,
      ItemCode: "BTS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Business Tour (Other Cost)",
      Depreciation_Rate: 100,
      ItemCode: "BTO",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Conference and Seminar Fees",
      Depreciation_Rate: 100,
      ItemCode: "CSF",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Employee Training and Development Programs",
      Depreciation_Rate: 100,
      ItemCode: "ETD",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Health and Wellness Programs",
      Depreciation_Rate: 100,
      ItemCode: "HWP",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Gym Memberships",
      Depreciation_Rate: 100,
      ItemCode: "GYM",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Team Building Activities",
      Depreciation_Rate: 100,
      ItemCode: "TBA",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Talent Acquisition",
      Depreciation_Rate: 100,
      ItemCode: "TAA",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Client Acquisition",
      Depreciation_Rate: 100,
      ItemCode: "CLA",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Employee Gifts & Rewards",
      Depreciation_Rate: 100,
      ItemCode: "EGR",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Office Events and Celebrations",
      Depreciation_Rate: 100,
      ItemCode: "OEC",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Cloud Storage Subscriptions",
      Depreciation_Rate: 100,
      ItemCode: "CSS",
      Frequency: "MONTH",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Antivirus and Security Software Subscriptions",
      Depreciation_Rate: 100,
      ItemCode: "ASS",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Domain Registration and Hosting Services",
      Depreciation_Rate: 100,
      ItemCode: "DRH",
      Frequency: "YEAR",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Fuel",
      Depreciation_Rate: 100,
      ItemCode: "FUE",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Courier",
      Depreciation_Rate: 100,
      ItemCode: "COU",
    },
    {
      Category: "OPERATIONAL_EXPENSE",
      Item: "Security Person",
      Depreciation_Rate: 100,
      ItemCode: "SEP",
      Frequency: "MONTH",
    },
  ];