name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install git (needed for SSH)
      - name: Install git
        run: sudo apt-get update && sudo apt-get install -y git

      # Step 3: Set up SSH keys
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 4: Set up Node.js (version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      # Step 5: Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install

      # Step 6: Install Serverless framework using Yarn
      - name: Install Serverless
        run: yarn global add serverless

      # Step 7: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 8: Deploy with Serverless (Development)
      - name: Deploy with Serverless (Development)
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          RESEND_API: ${{ secrets.RESEND_API }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OPENSSL_CONF: ${{ secrets.OPENSSL_CONF }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: serverless deploy --stage ${{ secrets.NODE_ENV }}
