name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger the deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # You can use any version of Node.js here

      # Step 3: Install Yarn
      - name: Install Yarn
        run: npm install -g yarn

      # Step 4: Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install

      # Step 5: Install Serverless Framework globally
      - name: Install Serverless
        run: yarn global add serverless

      # Step 6: Set up AWS credentials and profile
      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "region=ap-south-1" >> ~/.aws/config

      # Step 7: Deploy using Serverless
      - name: Deploy with Serverless (Production)
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          RESEND_API: ${{ secrets.RESEND_API }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          OPENSSL_CONF: ${{ secrets.OPENSSL_CONF }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_REGION: ap-south-1
        run: yarn deploy:directprod  # Make sure your deploy command in package.json is correct

