name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js (version 18)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      # Step 3: Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install
      
      - name: Unset AWS_PROFILE
        run: unset AWS_PROFILE

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 5: Deploy with Serverless Framework
      - name: Deploy with Serverless
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RESEND_API: ${{ secrets.RESEND_API }}
          OPENSSL_CONF: ${{ secrets.OPENSSL_CONF }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        run: npx serverless deploy --stage ${{ secrets.NODE_ENV }}
